{% set version = "1.11.0" %}

package:
  name: python3-saml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python3-saml/python3-saml-{{ version }}.tar.gz
  sha256: ec49f0216f75a379f7b3cd367d477321fa86e2a7e66801ee9e18c18fdd691ff2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - isodate >=0.5.0
    - xmlsec >=0.6.0
    - defusedxml >=0.5.0

test:
  imports:
    - onelogin
    - onelogin.saml2

about:
  home: https://github.com/onelogin/python3-saml
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Onelogin Python Toolkit. Add SAML support to your Python software using this library

extra:
  recipe-maintainers:
    - jaimergp
