{% set version = "1.13.0" %}

package:
  name: python3-saml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python3-saml/python3-saml-{{ version }}.tar.gz
  sha256: 95b32b66dff4b482871020b56037afea96e2551cbc0e1761722fed0aa7f60703

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - isodate >=0.5.0
    - xmlsec >=0.6.0
    - defusedxml >=0.5.0
    - lxml >=3.3.5

test:
  imports:
    - onelogin
    - onelogin.saml2

about:
  home: https://github.com/onelogin/python3-saml
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Onelogin Python Toolkit. Add SAML support to your Python software using this library

extra:
  recipe-maintainers:
    - jaimergp
